### ISSUE TITLE
No box in frontend with adress !!

### ISSUE THREAD

**Issue by vincegre** [michaelmcarthur/GoogleGeocode-HASS#13]
Hi

Thanks for sharing this great little tool that I have setup in my own HA and so far it looks to work excepted one thing: I have well a new round icon with my name and gravatar icon and when I click on it I can see current adress and history, but I don't have the square box appears with name and adress as displayed in your setup ! Did you do something extra ? Running on HA 0.51.2

My config:
```
- platform: google_geocode
    name: vincen
    origin: device_tracker.vincen_mqtt
    options: street_number, street, city, country
    display_zone: show
    gravatar: !email
    api_key: !google_geocode_api
```

Thanks

Vincèn

**Comment by michaelmcarthur** [comment]
To move the round icon to the square box simply add the Google Geocode sensor to a group.  Does this answer your problem? 

groups.yaml
```
Trackers:
   - sensor.donna
   - sensor.michael
```

**Comment by vincegre** [comment]
Well I added this in my main default group:

- device_tracker.vincen_mqtt

but not working :(

Update: replaced it with

- sensor.vincen

but same :( I get the round icon at top but not the square box in my states tabs !!

**Comment by michaelmcarthur** [comment]
As device tracker and sensor are both not working. It must be something to do with your groups.yaml. Do you have groups set up for other sensors? If you do have a working sensor in a group swap it out with the device tracker. If that does not work have a look through the [groups](https://home-assistant.io/components/group/) information. Let me know how you get on.

**Comment by vincegre** [comment]
I have some other sensors like temperature/humidity that displays correctly in that group:
![selection_001](https://user-images.githubusercontent.com/3164888/29408029-efc9799c-8346-11e7-8e3a-7039e067f44c.png)
and code:

> salon:
>   name: Salon
>   view: yes
>   entities:
>     - automation.lecture_pmp
>     - automation.pausearret_pmp
>     - binary_sensor.oeil_sensor
>     - binary_sensor.salon_radar_sensor
>     - light.canape_level
>     - media_player.ampli
>     - media_player.tv
>     - media_player.plex_web_chrome
>     - scene.salon_cinema
>     - scene.salon_normal
>     - scene.salon_off
>     - sensor.lierre_hum
>     - sensor.nuit
>     - sensor.salon_hum
>     - sensor.salon_temp
>     - sensor.vincen
>     - device_tracker.vincen_mqtt
>     - switch.imprimante_3d_switch
>     - switch.prise_clim_switch
>     - media_player.pmp_salon

So basically it should be correct no ? or am I missing something obvious ? I just discover groups :/

**Comment by michaelmcarthur** [comment]
Give this code a go:

```
salon:
name: Salon
view: yes
entities:
  - automation.lecture_pmp
  - automation.pausearret_pmp
  - binary_sensor.oeil_sensor
  - binary_sensor.salon_radar_sensor
  - light.canape_level
  - media_player.ampli
  - media_player.tv
  - media_player.plex_web_chrome
  - scene.salon_cinema
  - scene.salon_normal
  - scene.salon_off
  - sensor.lierre_hum
  - sensor.nuit
  - sensor.salon_hum
  - sensor.salon_temp
  - switch.imprimante_3d_switch
  - switch.prise_clim_switch
  - media_player.pmp_salo
  - group.trackers

trackers:
  - sensor.vincen
  - device_tracker.vincen_mqtt
```

**Comment by michaelmcarthur** [comment]
Closed due to issue not related to the component
