### ISSUE TITLE
Unable to use !tag for geocode and email !

### ISSUE THREAD

**Issue by vincegre** [michaelmcarthur/GoogleGeocode-HASS#14]
For security and ease of maintenance I store all sensible credentials in a separate secrets.yaml but it doesn't work for gravatar and api_key of your module ! HA complains it doesn't recognise unless it works with all other plugins, and configuration directive in my configuration.yaml file !

Vincèn

**Comment by michaelmcarthur** [comment]
Thanks for identifying this issue. I don't use secrets in my setup. I assumed that the core code took care of secrets. I'll have a look into this.

**Comment by vincegre** [comment]
Yep would have sounded logical but perhaps it's just a way you declare variables or something like that that makes them "secretable" ?

Side suggestion: it would be great to use an open API for geocoding like this one: https://developer.mapquest.com/documentation/open/geocoding-api/ (I don't like to use Google services that track you in all ways they can !!). I don't know if it's complicated to do ? or offer option in module settings ??

**Comment by michaelmcarthur** [comment]
I had a look at a few different services. Openstreetmap is my favourite. It gives place information as well. Meaning it will tell you the name of the cafe, shop or building you are in. It make it a lot easier to know where someone is. Most of the other services use openstreetmap's data and they have better usage policies. It's fairly easy to change the code to use different services. If you know what you are doing it can be done in about 10 minutes. My main goal is to get out this tried and tested component first. Make sure there is no more issues. Then I can add more services. This would be in the form of separate components for each service.

**Comment by michaelmcarthur** [comment]
I tried using secrets. I have tested it on 0.49 and 0.51.2. Both work on my system with secrets. Can you post the error log and any other relevant information. Thanks

**Comment by vincegre** [comment]
Oki tried it again and now it works ;) Sorry for that, don't know what happened or what I did wrong :(

**Comment by michaelmcarthur** [comment]
No worries. Your issue finally made me give secrets a go. I'm in the process of changing  all my passwords over to secrets. Thanks
