### ISSUE TITLE
Add Entity Picture Option

### ISSUE THREAD

**Issue by michaelmcarthur** [michaelmcarthur/GoogleGeocode-HASS#15]
User @prates said 

Excelent!
Used for just one day, and got the api limit error. Just got an API key to see if fix this. Also missing an option to choose a picture: it seems that picture or entity_picture doesn´t work as it does for device_tracker.

Add entity_picture as option

**Comment by bachya** [comment]
No components implement `entity_picture` directly ([minus a future version to the Template entities that I'm working on](https://github.com/home-assistant/home-assistant/pull/9792)) – the correct way to do this is via entity customization within HASS itself: https://home-assistant.io/docs/configuration/customizing-devices/

So, recommend we close this issue and don't worry implementing it here!

**Comment by michaelmcarthur** [comment]
I’m in agreement. It’s the way that I would add a picture to a sensor.
