### ISSUE TITLE
Person component integration

### ISSUE THREAD

**Issue by bachulator** [michaelmcarthur/GoogleGeocode-HASS#20]
The recent HA version introduced new component to make device_tracking association with users even more easier. https://www.home-assistant.io/components/person/

The component object seems to have same attributes for longitude and latitude but unfortunately google_geocode doesn't return any response when the person object is passed as origin. Any chance for implementation?

**Comment by michaelmcarthur** [comment]
Thanks for adding this change. I have not been active on github for a few months. Your change has been merged.
