### ISSUE TITLE
Change config to google_geocode folder - sensor.py

### ISSUE THREAD

**Issue by jokerigno** [michaelmcarthur/GoogleGeocode-HASS#22]

**Comment by Pirol62** [comment]
Have the same issue on HASS.io. 

Log Details (ERROR)
Wed Apr 24 2019 08:19:22 GMT+0200 (Mitteleuropäische Sommerzeit)
Integrations need to be in their own folder. Change sensor/google_geocode.py to google_geocode/sensor.py. This will stop working soon.

**Comment by Swiftnesses** [comment]
This actually requires some more changes to be compatible with future versions:

https://developers.home-assistant.io/docs/en/creating_integration_file_structure.html

**Comment by typendetinus** [comment]
Yeps, this stopped working as of 0.92 and no longer registers as a custom component

**Comment by michaelmcarthur** [comment]
Issue now resolved. Thanks for pointing out
